services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: dbname
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
