services:
    app:
        build: .
        ports:
            - ${PORT:-8080}:${PORT:-8080}
        environment:
            GOOSE_MIGRATION_DIR: /app/migrations
            GOOSE_DRIVER: postgres
            GOOSE_DBSTRING: "host=${DATABASE_HOST:-db} user=${DATABASE_USER:-postgres} dbname=${DATABASE_NAME:-scheduler} password=${DATABASE_PASS:-secret} sslmode=disable"
        volumes:
            - .:/app
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: ${DATABASE_USER:-postgres}
            POSTGRES_PASSWORD: ${DATABASE_PASS:-secret}
            POSTGRES_DB: ${DATABASE_NAME:-scheduler}
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
